version: 2

jobs:
  php70:
    working_directory: ~/home
    docker:
      - image: php:7.0-cli
    steps:
      - checkout
      - run:
          name: "Run something.php"
          command: 'php something.php'

  php71:
    docker:
      - image: php:7.1-cli
    steps:
      - checkout
      - run:
          name: "Run something.php"
          command: 'php something.php'

workflows:
  version: 2
  build:
    jobs:
      - php70:
          name: "php70-Symfony28"
          environment: "2.8"
      - php70:
          name: "php70-Symfony30"
          environment: "3.0"
      - php71:
          name: "php71-Symfony28"
          environment: "2.8"
      - php71:
          name: "php71-Symfony30"
          environment: "3.0"
